[marvell-teralynx] Enhance techsupport to include HWSKU configs (#4161)
* [marvell-teralynx] Enhance techsupport to include HWSKU configs

Description:

	This commit enhances the collect_marvell_teralynx() function in the
	generate_dump script to include HWSKU configuration files in the techsupport
	bundle for Marvell Teralynx platforms.

Changes:

	Copies all files (up to 2 levels deep) from the HWSKU directory
	(/usr/share/sonic/device/${platform}/${hwsku}) to the techsupport archive
	If common_config_support file exists in the HWSKU directory, collects all
	YAML files from /var/run/docker-syncd.

Signed-off-by: Naveen Rampuram <nrampuram@marvell.com>

* [marvell-teralynx] Fix minor review comments

Signed-off-by: Ravi Minnikanti <rminnikanti@marvell.com>

---------

Signed-off-by: Naveen Rampuram <nrampuram@marvell.com>
Signed-off-by: Ravi Minnikanti <rminnikanti@marvell.com>
Co-authored-by: rustiqly <245760149+rustiqly@users.noreply.github.com>
Co-authored-by: Ravi Minnikanti <rminnikanti@marvell.com>

diff --git a/scripts/generate_dump b/scripts/generate_dump
--- a/scripts/generate_dump
+++ b/scripts/generate_dump
@@ -1947,8 +1947,38 @@ collect_cisco_8000() {
 #   None
 ##############################################################################
 collect_marvell_teralynx() {
+    trap 'handle_error $? $LINENO' ERR
     save_cmd "ivmcmd 'show techsupport -i /innovium/show_techsupport_infile'" "show_techsupport_op_ifcs.log"
     save_cmd "ivmcmd 'show techsupport -i /innovium/show_techsupport_infile_iSAI'" "show_techsupport_op_iSAI.log"
+
+    local platform=$(show platform summary --json | python -c 'import sys, json; \
+        print(json.load(sys.stdin)["platform"])')
+    local hwsku=$(show platform summary --json | python -c 'import sys, json; \
+        print(json.load(sys.stdin)["hwsku"])')
+
+    if [ -d /usr/share/sonic/device/${platform}/${hwsku} ]; then
+        # copy all the files in the HWSKU directory
+        pushd /usr/share/sonic/device/${platform}/${hwsku} > /dev/null
+        for file in $(find . -maxdepth 2 -type f); do
+            save_file ${file} sai false
+        done
+        popd > /dev/null
+
+        if [ -f /usr/share/sonic/device/${platform}/${hwsku}/common_config_support ]; then
+            if [ -d /var/run/docker-syncd ]; then
+                for file in $(find /var/run/docker-syncd -type f -name "*.yaml"); do
+                    save_file ${file} sai false
+                done
+                # sai.profile - copy the final sai.profile generated in docker-syncd
+                if [ -f /var/run/docker-syncd/sai.profile ]; then
+                    save_file /var/run/docker-syncd/sai.profile sai false
+                fi
+            fi
+        fi
+    else
+        echo "'/usr/share/sonic/device/${platform}/${hwsku}' does not exist" > /tmp/error
+        save_file /tmp/error sai false
+    fi
 }
 
 ###############################################################################
